w4/musicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do 
  	resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do 
  	resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new] do
    resources :notes, only: [:new, :create, :destroy]
  end

  root to: 'bands#index'
end

w4/musicApp/app/views/shared/_album_form.html.erb
<% url = album.persisted? ? album_url(album) : albums_url %>
<% button_label = album.persisted? ? "Edit " : "Create " %>
<form action="<%= url %>" method="POST">
<% if album.persisted? %>
	<input type="hidden" name="_method" value="PATCH">
<% end %>
<%= auth_token %>
<p><label for="title">Title:</label>
<input type="text" name="album[title]" id="title"></p>
<p><label for="band">Band:</label>
<select name="album[band_id]" 
			 id="band">
<% bands.each do |band| %>
<option	value="<%= band.id %>"
	<%= "selected" if params[:band_id] == band.id.to_s %>><%= band.name %></option>
<% end %>
</select>
</p>

<p><label for="rec_type">Live:</label>
<input type="radio" 
			 name="album[rec_type]" 
			 id="live"
			 value="live"></p>

<p><label for="studio">Studio:</label>
<input type="radio" 
			 name="album[rec_type]" 
			 id="studio"
			 value="studio"></p>

<input type="submit" value="<%= button_label %>album!">
</form>

w4/musicApp/app/views/shared/_band_form.html.erb
<% action = band.persisted? ? band_url(band) : bands_url %>
<% button_label = band.persisted? ? "Edit " : "Add " %>

<form action="<%= action %>" method="POST">
<% if band.persisted? %>
	<input type="hidden" name="_method" value="PATCH">
<% end %>
<%= auth_token %>
<p><label for="name">Band name:</label>
<input type="text" 
			 name="band[name]" 
			 id="name"
			 value="<%= @band.name %>">
</p>

<input type="submit" value="<%= button_label %> band!">

w4/musicApp/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
	<ul>
	<% flash[:errors].each do |error| %>
				<li><%= error %></li>
	<% end %>
	</ul>
<% end %>

w4/musicApp/app/views/shared/_form.html.erb
<% url = action == "in" ? session_url : users_url %>

<form action="<%= url %>" method="POST">
<%= auth_token %>
<p><label for="email">Email:</label>
<input type="text" 
			 name="user[email]" 
			 id="email"></p>

<p><label for="password">Password:</label>
<input type="password" 
			 name="user[password]" 
			 id="password"></p>

<input type="submit" value="Sign <%= action %>!">

w4/musicApp/app/views/shared/_track_form.html.erb
<% url = track.persisted? ? track_url(track) : tracks_url %>
<% button_label = track.persisted? ? "Edit " : "Create " %>
<form action="<%= url %>" method="POST">
<% if track.persisted? %>
	<input type="hidden" name="_method" value="PATCH">
<% end %>
<%= auth_token %>
<p><label for="title">Title:</label>
<input type="text" name="track[title]" id="title"></p>

<p><label for="regular">Regular:</label>
<input type="radio" 
			 name="track[track_type]" 
			 id="regular"
			 value="regular"></p>

<p><label for="bonus">Bonus:</label>
<input type="radio" 
			 name="track[track_type]" 
			 id="bonus"
			 value="bonus"></p>

<input type="submit" value="<%= button_label %>track!">
</form>